language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_script:
- "gem install travis-artifacts"
script: phpunit Test.php
after_script:
  - "travis-artifacts upload --path logs --path a/long/nested/path:short_alias"
after_test:
  - "travis-artifacts upload --target-path artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
